"""Add mood fields to journal entries

Revision ID: 33d8f2db9d07
Revises: 
Create Date: 2025-05-16 15:52:26.097272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33d8f2db9d07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_mood', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mood_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('emotions', sa.Text(), nullable=True))
        batch_op.drop_column('mood_score')
        batch_op.drop_column('mood_tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_tags', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('mood_score', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('emotions')
        batch_op.drop_column('mood_confidence')
        batch_op.drop_column('primary_mood')

    # ### end Alembic commands ###
